version: '3.4'

services:
  sunoapi:
    image: ztbcs/sunoapi:latest
    container_name: sunoapi
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - ./template:/template
    environment:
      - PORT=9000
      - TZ=Asia/Shanghai
      - ROTATE_LOGS=false
      - PPROF=false
      - DEBUG=false
      - BASE_URL=https://xxx 
      - CHAT_TEMPLATE_DIR=./template
      - CHAT_OPENAI_MODEL=deepseek-chat
      - CHAT_OPENAI_BASE=https://api.deepseek.com
      - CHAT_OPENAI_KEY=sk-xxx

